# vim:ff=unix ts=2 sw=2 expandtab
---

- hosts: all
  connection: local
  gather_facts: False

  tasks:
    - set_fact: server_ami="{{ lookup('file', './ami_image.txt') | replace('\n', '') }}"
    - debug: msg="Using AMI '{{ server_ami }}'"

    - name: Fetching current DNS entry (to match up the elastic IP)
      shell: dig home.endlessm.com A +short | grep -v '[^0-9a-f\.\:]'
      register: dns_result
      when: server_elastic_ip is not defined

    - name: Setting the search IP
      set_fact: server_elastic_ip="{{ dns_result.stdout }}"
      when: server_elastic_ip is not defined

    - name: Fetching current deployment commit
      command: git rev-parse HEAD
      args:
        warn: no
      register: git_deploy_commit_result

    - name: Setting the deployment commit ID
      set_fact: deploy_commit="{{ git_deploy_commit_result.stdout }}"

    - name: Getting current deployment info
      ec2_remote_facts:
        filters:
          ip-address: "{{ server_elastic_ip }}"
          key_name: "{{ server_key }}"
        region: "{{ aws_region }}"
      register: ec2_instances

    - set_fact: old_instance_id="{{ ec2_instances.instances[0].id }}"

    - debug: msg="Old instance '{{ old_instance_id }}'"

    # XXX: WARNING! Mongo has no authentication on the server config
    #      so don't open 27017 to anything that isn't the aggregation
    #      infrastructure
    - ec2_group:
        name: "eos-activation-server"
        description: "Security group for the activation server"
        region: "{{ aws_region }}"
        rules:
          - cidr_ip: 0.0.0.0/0          # Allow SSH from anywhere
            proto: tcp
            from_port: 22
            to_port: 22
          - cidr_ip: 0.0.0.0/0          # Allow HTTP from anywhere
            proto: tcp
            to_port: 80
            from_port: 80
          - cidr_ip: 0.0.0.0/0          # Allow HTTPS from anywhere
            proto: tcp
            to_port: 443
            from_port: 443
          - cidr_ip: 52.25.206.231/32   # Mongo to HDP server (external)
            proto: tcp
            from_port: 27017
            to_port: 27017
          - cidr_ip: 172.31.8.54/32     # Mongo to HDP server (internal)
            proto: tcp
            from_port: 27017
            to_port: 27017
        rules_egress:
          - cidr_ip: 0.0.0.0/0
            proto: all

    - ec2_vol:
        instance: "{{ old_instance_id }}"
        state: list
        region: "{{ aws_region }}"
      register: volume_listing

    - set_fact:
        database_volume="{{ item.id }}"
        aws_zone="{{ item.zone }}"
      when: 'not item.attachment_set.device.endswith("sda1")'
      with_items: "{{ volume_listing.volumes | to_json }}"

    - debug: msg="Database Volume '{{ database_volume }}'"
    - debug: msg="Database Volume Zone '{{ aws_zone }}'"

    - name: Provisioning new instance
      ec2:
        region: "{{ aws_region }}"
        image: "{{ server_ami }}"
        key_name: "{{ server_key }}"
        instance_type: "{{ instance_type | default('t2.medium', False) }}"
        assign_public_ip: no
        group: "eos-activation-server"
        instance_tags:
          Name: eos-activation-server
          AMI: "{{ server_ami }}"
          DeployCommit: "{{ deploy_commit }}"
        # TODO: Use user data to set git token
        # user_data:
        termination_protection: yes
        wait: yes
        wait_timeout: 500
        zone: "{{ aws_zone }}"
      register: provisioning_result

    - set_fact: new_instance_id={{ provisioning_result.instance_ids[0] }}

    - debug: msg="New instance '{{ new_instance_id }}'"

    # XXX: Ansible doesn't have a way to do this through EC module yet
    - name: Disabling shutdown protection on old instance
      command: >
        aws ec2 modify-instance-attribute
          --region "{{ aws_region }}"
          --instance-id "{{ old_instance_id }}"
          --attribute disableApiTermination --value false

    # XXX: Try to shut down the instance before wiping it but we
    #      currently can't since the volume doesn't want to detach on stop
    #      Upstream: https://github.com/ansible/ansible/issues/4127
    - name: Terminating the old instance
      ec2:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ old_instance_id }}"
        state: absent
        wait: yes
        wait_timeout: 500

    - name: Attaching old volume to new instance
      ec2_vol:
        region: "{{ aws_region }}"
        instance: "{{ new_instance_id }}"
        id: "{{ database_volume }}"

      # XXX: Restarted state not in mainline even though it's in docs :/
    - name: Restarting new instance (1/2)
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ new_instance_id }}"
        state: stopped
        wait: yes
        wait_timeout: 500

    - name: Restarting new instance (2/2)
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ new_instance_id }}"
        state: running
        wait: yes
        wait_timeout: 500

    - name: Forwarding the elastic IP to the new instance
      ec2_eip:
        region: "{{ aws_region }}"
        public_ip: "{{ server_elastic_ip }}"
        device_id: "{{ new_instance_id }}"
        in_vpc: yes
        reuse_existing_ip_allowed: yes
