#!/usr/bin/env node
// Copyright © 2016-2024 Endless OS Foundation LLC
// SPDX-License-Identifier: GPL-2.0-or-later

const config = require('./config');
var http = require("http");

var options = {
    host     : config.server_bind_address,
    method   : "GET",
    path     : "/health",
    port     :  config.server_port,
    timeout  : 5,
};

var request = http.request(options, (res) => {
    console.log(`STATUS: ${res.statusCode}`);
    if ((res.statusCode >= 200) && (res.statusCode < 500)) {
        process.exit(0);
    }
    else {
        process.exit(1);
    }
});

request.on('error', function(err) {
    console.log('ERROR: %s', err);
    process.exit(1);
});

request.end();
