#!/usr/bin/env node

const config = require('./config');
var http = require("http");

var options = {
    host     : config.server_bind_address,
    method   : "GET",
    path     : "/",
    port     :  config.server_port,
    timeout  : 5,
};

var request = http.request(options, (res) => {
    console.log(`STATUS: ${res.statusCode}`);
    if ((res.statusCode >= 200) && (res.statusCode < 500)) {
        process.exit(0);
    }
    else {
        process.exit(1);
    }
});

request.on('error', function(err) {
    console.log('ERROR');
    process.exit(1);
});

request.end();

